# Usar a imagem base do Python
FROM python:3.8

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o código fonte para o contêiner
COPY . /app

# Comando para executar o script Python
CMD ["python", "./client.py"] 
