version: "3"

services:
  server:
    build: .
    ports:
      - "12345:12345"
    network_mode: "host"
    volumes:
      - ./resource.txt:/app/resource.txt

  cliente1:
    build: .
    command: python3 -u start_election.py 1 12346 12347
    network_mode: "host"
    ports:
      - "12346:12346"

    depends_on:
      - server

  cliente2:
    build: .
    command: python3 -u client.py 2 12347 12348
    ports:
      - "12347:12347"
    network_mode: "host"
    depends_on:
      - server
      - cliente1

  cliente3:
    build: .
    command: python3 -u client.py 3 12348 12349
    network_mode: "host"
    ports:
      - "12348:12348"
    depends_on:
      - server
      - cliente2

  cliente4:
    build: .
    command: python3 -u client.py 4 12349 12346
    network_mode: "host"
    ports:
      - "12349:12349"

    depends_on:
      - server
      - cliente3
