version: "3"

services:
  server:
    build: .
    ports:
      - "12345:12345"
    network_mode: host
    volumes:
      - ./resource.txt:/app/resource.txt

  cliente1:
    build: .
    command: python3 -u client.py 1
    network_mode: host
    depends_on:
      - server

  cliente2:
    build: .
    command: python3 -u client.py 2
    network_mode: host
    depends_on:
      - server

  cliente3:
    build: .
    command: python3 -u client.py 3
    network_mode: host
    depends_on:
      - server

  cliente4:
    build: .
    command: python3 -u client.py 4
    network_mode: host
    depends_on:
      - server
